# Server
server:
  port: ${SERVER_PORT:9377}
  tomcat:
    # 连接建立后，等待客户端发送HTTP请求头超时
    connection-timeout: 30s
    # Keep-Alive 长连接空闲超时（请求处理完，等待下一次请求）
    keep-alive-timeout: 20s
spring:
  application:
    name: crabc-api
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    core:
      recycler-pool: thread-local  # Jackson3性能恢复
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/crabc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.crabc.core.admin.entity
  # 配置 mapper 扫描，找到所有 mapper.xml 映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

pagehelper:
  autoRuntimeDialect: true   # 开启多数据源分页识别


crabc:
  api-log:
    response-body: false  # 日志是否保存响应结果
